# Generated by Django 4.1.2 on 2022-10-31 14:00

import django.db.models.deletion
import utils.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coworking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoworkingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("altText", models.TextField(blank=True, null=True)),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                ("hashtags", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads_images/coworkings/"
                    ),
                ),
                (
                    "coworking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coworking.coworking",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, utils.mixins.AuditMixin),
        ),
    ]
