version: '3'
services:
  database:
    image: "postgres"
    volumes:
      - coworkings_database-data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  coworkings_database-data:
