# Generated by Django 4.1.2 on 2022-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_remove_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
