# Generated by Django 4.1.2 on 2022-11-17 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_reservation_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="total_price",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
