# Generated by Django 4.1.2 on 2022-11-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0004_remove_reservation_total_price_reservation_end_time_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_time",
        ),
    ]
