# Generated by Django 4.1.2 on 2022-10-31 14:00

import django.db.models.deletion
import utils.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coworking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads_images/coworkings/"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Verified"),
                            (2, "Not Verified"),
                            (3, "Temporarily Closed"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, utils.mixins.AuditMixin),
        ),
    ]
