# Generated by Django 4.1.2 on 2022-11-08 19:04

import django.db.models.deletion
import utils.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coworking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads_images/coworkings/"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Verified"),
                            (2, "Not Verified"),
                            (3, "Temporarily Closed"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "city")},
            },
            bases=(utils.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CoworkingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("altText", models.TextField(blank=True, null=True)),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads_images/coworkings/")),
                (
                    "coworking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coworking_photo",
                        to="coworking.coworking",
                    ),
                ),
                ("hashtags", models.ManyToManyField(blank=True, to="utils.hashtag")),
            ],
            bases=(utils.mixins.AuditMixin, models.Model),
        ),
    ]
