# Generated by Django 4.1.2 on 2022-11-01 11:30

import utils.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(utils.mixins.AuditMixin, models.Model),
        ),
    ]
